import type {
  ScenePublic,
  TranscriptEntry,
} from "@mighty-decks/spec/adventureState";
import { TranscriptFeed } from "./TranscriptFeed";

export const SAMPLE_SCENE: ScenePublic = {
  sceneId: "scene-sample-echoes",
  imageUrl: "/scenes/defending-an-underground-village.jpg",
  imagePending: false,
  closingImagePending: false,
  mode: "high_tension",
  tension: 78,
  activeActorPlayerId: "player-ralph",
  activeActorName: "Ralph Stoneshard",
  introProse:
    "The guttural roars echo through the cavernous entrance of Khaz'Drak. Dust rains from the crumbling ceiling as the earth trembles. Behind you, desperate villagers flee while you hold the line.",
  orientationBullets: [
    "Hold the breach long enough for the villagers to escape.",
    "A larger alpha creature coordinates the goblin surge.",
  ],
};

export const SAMPLE_TRANSCRIPT: TranscriptEntry[] = [
  {
    entryId: "sample-1",
    kind: "storyteller",
    author: "Storyteller",
    text: "The creatures are breaking through! What do you do to hold the line, and why is protecting these villagers so vital to you?",
    createdAtIso: "2026-02-15T20:00:08.000Z",
  },
  {
    entryId: "sample-2",
    kind: "storyteller",
    author: "Storyteller",
    text: "The creatures are breaking through! What do you do to hold the line, and why is protecting these villagers so vital to you?",
    createdAtIso: "2026-02-15T20:00:08.000Z",
  },
  {
    entryId: "sample-3",
    kind: "player",
    author: "Ralph Stoneshard",
    text: "I slam my shield and roar a dwarven warcry, then charge the front rank to rally the defenders.",
    createdAtIso: "2026-02-15T20:00:19.000Z",
  },
  {
    entryId: "sample-4",
    kind: "storyteller",
    author: "Storyteller",
    text: "Ralph Stoneshard, play an Outcome card. Charging a fortified front rank under immediate pressure is high risk and uncertain.",
    createdAtIso: "2026-02-15T20:00:24.000Z",
  },
  {
    entryId: "sample-5",
    kind: "system",
    author: "System",
    text: "Ralph Stoneshard played Outcome card: Partial Success (+1 Effect).",
    createdAtIso: "2026-02-15T20:00:29.000Z",
  },
  {
    entryId: "sample-6",
    kind: "storyteller",
    author: "Storyteller",
    text: "Your warcry snaps the defenders back into formation and the first goblin line buckles under your charge. But the alpha beast shifts to flank your position, forcing you to choose between pressing forward or protecting your side.",
    createdAtIso: "2026-02-15T20:00:37.000Z",
  },
  {
    entryId: "sample-7",
    kind: "player",
    author: "Ralph Stoneshard",
    text: "I pivot to intercept the alpha before it can break our line.",
    createdAtIso: "2026-02-15T20:00:45.000Z",
  },
];

export const SampleSession = (): JSX.Element => {
  return (
    <TranscriptFeed
      {...{
        entries: [
          /* {
            entryId: "t-mlod79l4-aees7m",
            kind: "system",
            author: "System",
            text: "Adventure pitches generated. Waiting for votes.",
            createdAtIso: "2026-02-15T23:16:41.416Z",
          }, */
          {
            entryId: "t-mlod7wz0-4dpiqi",
            kind: "system",
            author: "System",
            text: "Adventure selected: The Maw of the Mountain.",
            createdAtIso: "2026-02-15T23:17:11.724Z",
          },
          {
            entryId: "t-mlod7y84-6crc9x",
            kind: "storyteller",
            author: "Storyteller",
            text: "What do you do now, Ralph, and why do you brave the dragon's maw?",
            createdAtIso: "2026-02-15T23:17:13.348Z",
          },
          {
            entryId: "t-mlodb3gm-qohzz3",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I heard there is treasure. So count me in! What do I see?",
            createdAtIso: "2026-02-15T23:19:40.102Z",
          },
          {
            entryId: "t-mlodb6ni-522v2u",
            kind: "storyteller",
            author: "Storyteller",
            text: "The promise of treasure is a potent motivator. The immediate reality, however, is a cavern of fractured rock and dust. Your keen dwarven eyes discern the glimmer of scattered gold coins and a few ornate goblets half-buried beneath rubble near the far wall. The air, thick with the dragon's presence, is also surprisingly still. You are in a roughly circular chamber, perhaps fifty feet across. The ceiling above you has a fresh, jagged tear, marking the cave-in. Opposite you, a wider, darker opening promises passage deeper into the mountain's depths, or perhaps, the dragon's lair itself.\nWhat do you do next to secure your treasure?",
            createdAtIso: "2026-02-15T23:19:44.238Z",
          },
          {
            entryId: "t-mlodc8bp-5uys3q",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I follow the gold coins",
            createdAtIso: "2026-02-15T23:20:33.061Z",
          },
          {
            entryId: "t-mlodc8y5-qnlnp5",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Following treasure into a dragon's lair is high reward and uncertain.",
            createdAtIso: "2026-02-15T23:20:33.869Z",
          },
          {
            entryId: "t-mlodcayg-d1xn4h",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Fumble (-1 Effect).",
            createdAtIso: "2026-02-15T23:20:36.472Z",
          },
          {
            entryId: "t-mlodcdif-qi525m",
            kind: "storyteller",
            author: "Storyteller",
            text: "Your focus on the gold coins leads you to overlook a crucial detail. As you step towards the scattered treasure, your boot dislodges a loose rock, which tumbles into a hidden crevice. The sound echoes, far louder than it should, and a low, guttural rumble answers from the dark opening across the chamber. The dragon is aware of your presence. You have gained no treasure, and now its attention is fixed upon you. What do you do?",
            createdAtIso: "2026-02-15T23:20:39.783Z",
          },
          {
            entryId: "t-mlodcdig-t26ut5",
            kind: "system",
            author: "System",
            text: "Tension spikes. Turn order tightens and immediate actions matter.",
            createdAtIso: "2026-02-15T23:20:39.784Z",
          },
          {
            entryId: "t-mlodcdig-0mjhfw",
            kind: "system",
            author: "System",
            text: "High tension turn order: Ralph Stoneshard acts next.",
            createdAtIso: "2026-02-15T23:20:39.784Z",
          },
          {
            entryId: "t-mloddpjj-w3drkk",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I keep following the coins",
            createdAtIso: "2026-02-15T23:21:42.031Z",
          },
          {
            entryId: "t-mloddvhu-z0sdz3",
            kind: "storyteller",
            author: "Storyteller",
            text: "You continue to follow the glittering trail of coins. Each step takes you closer to the dark opening, the source of the recent rumble. The air grows heavier, warmer, and a faint, acrid smell of sulfur becomes more pronounced. The coins lead directly into the maw of the deeper passage. You are now at the threshold of the dragon's inner lair.\nWhat do you do?",
            createdAtIso: "2026-02-15T23:21:49.746Z",
          },
          {
            entryId: "t-mloddvhv-xmhs1d",
            kind: "system",
            author: "System",
            text: "High tension turn order: Ralph Stoneshard acts next.",
            createdAtIso: "2026-02-15T23:21:49.747Z",
          },
          {
            entryId: "t-mlodebew-4pnnut",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I walz in",
            createdAtIso: "2026-02-15T23:22:10.376Z",
          },
          {
            entryId: "t-mlodec02-la99cs",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Entering a dragon's lair directly is a high-risk, high-reward action with immediate threat.",
            createdAtIso: "2026-02-15T23:22:11.138Z",
          },
          {
            entryId: "t-mlodedzx-891dm5",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Chaos (Sudden Change).",
            createdAtIso: "2026-02-15T23:22:13.725Z",
          },
          {
            entryId: "t-mlodegjt-7a5yrz",
            kind: "storyteller",
            author: "Storyteller",
            text: "Despite your casual stride into the lair, an unexpected shift occurs. Instead of the expected fiery breath or immediate monstrous roar, an immense, leathery wing, previously hidden by the cavern's contours, sweeps down. It doesn't strike you, but rather dislodges a massive, ancient stalactite directly in your path. The stalactite crashes with a deafening boom, sealing the narrow passage behind you, not letting you \"walz in\" any further, but instead blocking any retreat. The lair itself remains silent, yet you are now utterly confined.\nWhat do you do?",
            createdAtIso: "2026-02-15T23:22:17.033Z",
          },
          {
            entryId: "t-mlodegjt-3nkzxv",
            kind: "system",
            author: "System",
            text: "Direct scrutiny ends. Players may act freely while the queue is clear.",
            createdAtIso: "2026-02-15T23:22:17.033Z",
          },
          {
            entryId: "t-mlodh96b-5b41uk",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I take out my shield I had made fire resistant in preparation for this endeavor and a maul blessed by the forgemaster himself to help me on my worthy quest. I move further into the lair",
            createdAtIso: "2026-02-15T23:24:27.443Z",
          },
          {
            entryId: "t-mlodha2z-rmvpfj",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Moving further into the lair after a cave-in and with a dragon potentially present is a direct action with immediate threat and uncertainty.",
            createdAtIso: "2026-02-15T23:24:28.619Z",
          },
          {
            entryId: "t-mlodhe7f-kkqfoa",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Partial Success (+1 Effect).",
            createdAtIso: "2026-02-15T23:24:33.963Z",
          },
          {
            entryId: "t-mlodhguc-eoc1vg",
            kind: "storyteller",
            author: "Storyteller",
            text: "The weight of your shield and maul feels reassuringly familiar as you ready them. Each step further into the cavern opens up more of the vast chamber, revealing glints of gold and a faint, acrid smell. However, the ground beneath your boots shifts unexpectedly. A section of the floor gives way, not enough to trap you, but revealing a narrow, unstable crevice running across your path. You must navigate this new obstacle before proceeding deeper. What do you do?",
            createdAtIso: "2026-02-15T23:24:37.380Z",
          },
          {
            entryId: "t-mlodi6ye-vgezka",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I go around",
            createdAtIso: "2026-02-15T23:25:11.222Z",
          },
          {
            entryId: "t-mlodi7t9-xugjn0",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Navigating an unstable crevice in a dragon's lair presents immediate threat and uncertainty.",
            createdAtIso: "2026-02-15T23:25:12.333Z",
          },
          {
            entryId: "t-mlodideb-tu28of",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Partial Success (+1 Effect).",
            createdAtIso: "2026-02-15T23:25:19.571Z",
          },
          {
            entryId: "t-mlodigmx-nnw4zq",
            kind: "storyteller",
            author: "Storyteller",
            text: "You successfully find a path around the unstable crevice. It costs you precious time and forces you to hug the cavern wall. As you round a large outcropping, the chamber opens further, revealing a massive, slumbering form coiled amidst a hoard of treasure. Its scales shimmer with an inner fire, and a low rumble vibrates through the stone. You are now closer to the dragon than you intended to be, and its sheer size is staggering. What do you do?",
            createdAtIso: "2026-02-15T23:25:23.769Z",
          },
          {
            entryId: "t-mlodkowm-c11ttx",
            kind: "player",
            author: "Ralph Stoneshard",
            text: 'On the contrary, I am not close enough. I come towards the sleeping dragon and shout into its ear: "Ey, sleepy-head, waky waky, life\'s at stake! I challenge you to a duel!"',
            createdAtIso: "2026-02-15T23:27:07.798Z",
          },
          {
            entryId: "t-mlodkptb-5l14dm",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Directly provoking a sleeping dragon is high threat and high uncertainty.",
            createdAtIso: "2026-02-15T23:27:08.975Z",
          },
          {
            entryId: "t-mlodkvl5-4ud7ag",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Partial Success (+1 Effect).",
            createdAtIso: "2026-02-15T23:27:16.457Z",
          },
          {
            entryId: "t-mlodkylh-oicrne",
            kind: "storyteller",
            author: "Storyteller",
            text: "Your booming challenge echoes through the cavern, a defiant call against the oppressive silence. The dragon's massive head twitches, a low growl rumbling deep within its chest, stirring the piles of gold. One eye, a sliver of molten gold, slowly cracks open, fixing on you. You have its attention, but the sudden shift in its weight sends a cascade of ancient coins and jewels clattering down the hoard, creating a small, treacherous avalanche between you and the now-waking beast. You must consider how to cross the shifting treasure to fully engage the dragon.",
            createdAtIso: "2026-02-15T23:27:20.357Z",
          },
          {
            entryId: "t-mlodn9ff-35gnhe",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I guess the dragon didn't hear me. I light a stick of dynamite and chug it at the dragon. With the coins lying around, it could make quite a mess. I hide behind my shield and stay put.",
            createdAtIso: "2026-02-15T23:29:07.707Z",
          },
          {
            entryId: "t-mlodnaew-lr3pdt",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Directly attacking a waking dragon with dynamite is high threat and high uncertainty.",
            createdAtIso: "2026-02-15T23:29:08.984Z",
          },
          {
            entryId: "t-mlodnlxd-fhhojg",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Success (+2 Effect).",
            createdAtIso: "2026-02-15T23:29:23.905Z",
          },
          {
            entryId: "t-mlodnp2r-gmw9m2",
            kind: "storyteller",
            author: "Storyteller",
            text: "The lit dynamite stick arcs through the air, landing amidst the dragon's hoard with a fizzing fuse. The explosion is deafening, a concussive blast that sends gold coins and ancient relics spraying like shrapnel. The sheer force of the detonation, amplified by the confined space, rattles the cavern walls. The dragon, momentarily stunned, lets out a pained roar, its head thrashing. A significant portion of its treasure is now scattered and smoking, and the beast is clearly agitated. You have successfully inflicted damage and disrupted its composure. The dragon, now fully awake and enraged, glares at you with both eyes, smoke curling from its nostrils. What do you do next?",
            createdAtIso: "2026-02-15T23:29:27.987Z",
          },
          {
            entryId: "t-mlodozsm-5mk33e",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I look around for some useful relics",
            createdAtIso: "2026-02-15T23:30:28.534Z",
          },
          {
            entryId: "t-mlodp2vk-dizkm3",
            kind: "storyteller",
            author: "Storyteller",
            text: "The dragon's enraged roars echo through the cavern. You scan the chaos of scattered treasure, seeking something beyond mere gold. Amidst the chaos, a tarnished, yet ornate, dwarven war-axe lies half-buried, its blade still keen. It pulses faintly with an ancient, forgotten magic. You could attempt to retrieve it.",
            createdAtIso: "2026-02-15T23:30:32.528Z",
          },
          {
            entryId: "t-mlodpme8-zphp1q",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I grab it",
            createdAtIso: "2026-02-15T23:30:57.824Z",
          },
          {
            entryId: "t-mlodpn8a-h9jy05",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Grabbing a relic from a dragon's hoard after an explosion is high-stakes and uncertain.",
            createdAtIso: "2026-02-15T23:30:58.906Z",
          },
          {
            entryId: "t-mlodpobq-oyed4i",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Fumble (-1 Effect).",
            createdAtIso: "2026-02-15T23:31:00.326Z",
          },
          {
            entryId: "t-mlodpq4y-1yr4s7",
            kind: "storyteller",
            author: "Storyteller",
            text: "As you lunge for the war-axe, your fingers brush the cold metal just as the enraged dragon's tail whips across the cavern floor. The blow isn't direct, but the concussive force sends you sprawling, the axe skittering out of reach. You land hard against a pile of gold, momentarily winded. The dragon's roar vibrates through your bones. You are alive, but the axe is further away, and the dragon is now fully focused on you, its massive head lowering.\nThe war-axe still pulses with faint magic, a tantalizing prize amidst the chaos. What do you do next?",
            createdAtIso: "2026-02-15T23:31:02.674Z",
          },
          {
            entryId: "t-mlodrfnw-bt4g9w",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I charge the dragon while it's on the ground and smack it with my blessed maul",
            createdAtIso: "2026-02-15T23:32:22.412Z",
          },
          {
            entryId: "t-mlodrgyn-f4s9pm",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Charging a dragon on the ground is a direct confrontation with high threat and uncertainty.",
            createdAtIso: "2026-02-15T23:32:24.095Z",
          },
          {
            entryId: "t-mlodri60-g62f7n",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Success (+2 Effect).",
            createdAtIso: "2026-02-15T23:32:25.656Z",
          },
          {
            entryId: "t-mlodrkyx-74fqjg",
            kind: "storyteller",
            author: "Storyteller",
            text: "You surge forward, maul held high and glowing with a divine aura. The dragon, still recovering from the blast and its tail whip, turns its head, but not quickly enough. Your blessed maul connects with a sickening crunch against its jaw, a shower of scales and sparks erupting from the impact. The beast bellows, a sound of agony mixed with fury, and its head snaps back, momentarily stunned. A clear path to its vulnerable underbelly seems to open.\nWhat do you do next?",
            createdAtIso: "2026-02-15T23:32:29.289Z",
          },
          {
            entryId: "t-mlodtdjt-u4xt70",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I turn to smack it into the underbelly",
            createdAtIso: "2026-02-15T23:33:52.985Z",
          },
          {
            entryId: "t-mlodtef8-rstn92",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Directly attacking a stunned dragon's vulnerable underbelly presents immediate threat and high reward.",
            createdAtIso: "2026-02-15T23:33:54.116Z",
          },
          {
            entryId: "t-mlodtf8k-yg57x4",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Fumble (-1 Effect).",
            createdAtIso: "2026-02-15T23:33:55.172Z",
          },
          {
            entryId: "t-mlodthwl-o7qz9m",
            kind: "storyteller",
            author: "Storyteller",
            text: "You pivot, aiming for the exposed flesh, but your momentum carries you slightly off-balance. The dragon, though stunned, instinctively twitches. Your maul glances off a thick, unexpectedly resilient fold of skin on its flank, rather than the soft underbelly. The blow sends a jarring vibration up your arms, and the beast lets out a pained snarl, its head beginning to rise. The brief opening is lost, and the dragonâ€™s eye swivels to fix on you with renewed malice.\nThe dragon begins to gather itself, its massive form tensing. What is your next move as it recovers?",
            createdAtIso: "2026-02-15T23:33:58.629Z",
          },
          {
            entryId: "t-mlodvdgg-r5df2x",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I take out a throwing axe and hurl it at it's eye",
            createdAtIso: "2026-02-15T23:35:26.176Z",
          },
          {
            entryId: "t-mlodve8x-6zctja",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Directly attacking a dragon's eye is a high-risk, high-reward action with immediate threat.",
            createdAtIso: "2026-02-15T23:35:27.201Z",
          },
          {
            entryId: "t-mlodvh8x-pweejy",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Success (+2 Effect).",
            createdAtIso: "2026-02-15T23:35:31.089Z",
          },
          {
            entryId: "t-mlodvk9f-14x57c",
            kind: "storyteller",
            author: "Storyteller",
            text: "You seize a throwing axe, its polished edge glinting in the dim light, and launch it with a powerful, desperate throw. The axe spins true, a silver streak against the dragon's recovering form. It strikes the beast with a wet thud, not in the eye, but deeply into the soft flesh just below, embedding itself with surprising force. The dragon recoils violently, a shriek of pain tearing through the cavern, its head jerking away from you. Though not blinded, the wound is significant, forcing the creature to re-evaluate its immediate attack. Its focus now shifts, a new, more cautious anger simmering in its gaze.\nWhat do you do next, as the dragon hesitates, wounded and enraged?",
            createdAtIso: "2026-02-15T23:35:34.995Z",
          },
          {
            entryId: "t-mlody2e2-coxohg",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I run up it's tail and jump to smack it's head from the top with my blessed maul",
            createdAtIso: "2026-02-15T23:37:31.802Z",
          },
          {
            entryId: "t-mlody59p-e3k93g",
            kind: "storyteller",
            author: "Storyteller",
            text: "You quickly assess the dragon's momentarily disoriented state. As it thrashes, its tail whips close. You seize the opportunity, scrambling up the thick, scaly appendage, using its uneven surface for purchase. You reach the base of its back, a perilous perch. From there, you leap, maul raised high, aiming to bring the full force of your blessed weapon down upon its skull.\nWhat is your next move as you sail through the air towards the dragon's head?",
            createdAtIso: "2026-02-15T23:37:35.533Z",
          },
          {
            entryId: "t-mlodzqtd-c6ugcm",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I channel my ancestors for an extra umph on the strike at the dragon's head",
            createdAtIso: "2026-02-15T23:38:50.113Z",
          },
          {
            entryId: "t-mlodzrkb-4zlpmb",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. High-stakes direct action against a wounded, enraged dragon with a risky maneuver.",
            createdAtIso: "2026-02-15T23:38:51.083Z",
          },
          {
            entryId: "t-mlodztbt-8oyk40",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Special Action (+3 Effect).",
            createdAtIso: "2026-02-15T23:38:53.369Z",
          },
          {
            entryId: "t-mlodzvqr-lv5uvp",
            kind: "storyteller",
            author: "Storyteller",
            text: "As you channel your ancestors, a surge of primal strength courses through you. The maul, already blessed, seems to hum with ancient power. You land squarely on the dragon's skull, the impact jarring through your arms, but the blow is devastating. A sickening crack echoes, and the dragon roars, a sound now laced with true agony and a growing desperation. Its massive head lolls, and it stumbles, momentarily disoriented, giving you a precious opening.\nWhat do you do next, with the dragon reeling from your powerful strike?",
            createdAtIso: "2026-02-15T23:38:56.499Z",
          },
          {
            entryId: "t-mloe1swk-y4xgu3",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I gave it my best, I am exhausted, but I try to finish the dragon anyway",
            createdAtIso: "2026-02-15T23:40:26.132Z",
          },
          {
            entryId: "t-mloe1tow-z7wt3h",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Direct action against a wounded, enraged dragon with high stakes for victory or defeat.",
            createdAtIso: "2026-02-15T23:40:27.152Z",
          },
          {
            entryId: "t-mloe1ucb-pmcp2h",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Fumble (-1 Effect).",
            createdAtIso: "2026-02-15T23:40:27.995Z",
          },
          {
            entryId: "t-mloe1wnh-cuhpc9",
            kind: "storyteller",
            author: "Storyteller",
            text: "Your exhaustion, combined with the dragon's desperate lurch, causes your final, determined swing to go wildly off target. Instead of the dragon's skull, your maul strikes a stalagmite, shattering it with a deafening crack. The dragon, though still wounded and disoriented, regains a measure of its senses, its eyes narrowing on you with renewed fury. Its low growl rumbles through the cavern, promising retaliation.\nYou must now find a new approach or face its immediate wrath.",
            createdAtIso: "2026-02-15T23:40:30.989Z",
          },
          {
            entryId: "t-mloe2rwu-yh3pjp",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I try another exhausted swing",
            createdAtIso: "2026-02-15T23:41:11.502Z",
          },
          {
            entryId: "t-mloe2sqi-gpwyps",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Direct action against a dangerous foe after a previous fumble, high stakes for immediate threat and uncertainty.",
            createdAtIso: "2026-02-15T23:41:12.570Z",
          },
          {
            entryId: "t-mloe2tl3-ook25o",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Fumble (-1 Effect).",
            createdAtIso: "2026-02-15T23:41:13.671Z",
          },
          {
            entryId: "t-mloe2w5n-8oz547",
            kind: "storyteller",
            author: "Storyteller",
            text: "Your second exhausted swing, a testament to your unwavering will, again goes awry. The maul glances off the cavern wall, sending a shower of sparks and stone chips. The dragon, now fully aware, lowers its massive head, a guttural sound rumbling in its throat. Its eyes, burning with malevolent intelligence, fixate on you, preparing a counter-attack.\nYou find yourself vulnerable, the maul briefly stuck in the rock.",
            createdAtIso: "2026-02-15T23:41:17.003Z",
          },
          {
            entryId: "t-mloe2w5o-bt0c64",
            kind: "system",
            author: "System",
            text: "High tension turn order: Ralph Stoneshard acts next.",
            createdAtIso: "2026-02-15T23:41:17.004Z",
          },
          {
            entryId: "t-mloe50cc-v1njl8",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I abandon the maul and take out a repeating crossbow. A marvel of dwarven egineering armed with armour-piercing bolts. I open a salvo at the dragon.",
            createdAtIso: "2026-02-15T23:42:55.740Z",
          },
          {
            entryId: "t-mloe516g-lkr18s",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Direct attack on a dragon in high tension, immediate threat and high reward.",
            createdAtIso: "2026-02-15T23:42:56.824Z",
          },
          {
            entryId: "t-mloe53e1-u5rjrs",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Success (+2 Effect).",
            createdAtIso: "2026-02-15T23:42:59.689Z",
          },
          {
            entryId: "t-mloe55qq-czl3pk",
            kind: "storyteller",
            author: "Storyteller",
            text: "You swiftly abandon the embedded maul, drawing your repeating crossbow with practiced ease. The mechanism whirs as armour-piercing bolts load. With a series of sharp thwacks, the bolts find their mark, embedding themselves in the dragon's scales. The creature recoils, a hiss of pain escaping its fanged maw as smoke begins to curl from the impacted areas, a testament to the bolts' potency. The dragonâ€™s attention is now fully diverted to the new, stinging assault.\nWhat is your next action?",
            createdAtIso: "2026-02-15T23:43:02.738Z",
          },
          {
            entryId: "t-mloe55qr-faj2mg",
            kind: "system",
            author: "System",
            text: "Direct scrutiny ends. Players may act freely while the queue is clear.",
            createdAtIso: "2026-02-15T23:43:02.739Z",
          },
          {
            entryId: "t-mloe71bo-omft8r",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I see the dragon will go for an attack. There is a precarious stalactite hanging from the cavern ceiling. I want to shoot it off, so that it strikes the dragon as it is going for an attack",
            createdAtIso: "2026-02-15T23:44:30.324Z",
          },
          {
            entryId: "t-mloe726h-gvox8y",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. High-tension scene with direct threat and high reward. The action directly targets the dragon during an attack.",
            createdAtIso: "2026-02-15T23:44:31.433Z",
          },
          {
            entryId: "t-mloe73rs-o1fxjf",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Partial Success (+1 Effect).",
            createdAtIso: "2026-02-15T23:44:33.496Z",
          },
          {
            entryId: "t-mloe76pr-wyoosn",
            kind: "storyteller",
            author: "Storyteller",
            text: "The dragonâ€™s head dips, its eyes fixing on you with predatory intent, and a low growl begins to rumble in its chest. You aim for the colossal stalactite, a dark spear hanging precariously above the beast. Your bolts splinter the ancient rock, sending a shower of smaller debris down. The stalactite cracks further, but does not immediately fall. The dragon, momentarily distracted by the new rain of stone, hesitates, its attack delayed but not averted. The instability of the ceiling has now been compromised, adding a new layer of danger to the cavern.\nWhat do you do next?",
            createdAtIso: "2026-02-15T23:44:37.311Z",
          },
          {
            entryId: "t-mloe7ve8-s4z4jh",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I shoot at the dragon",
            createdAtIso: "2026-02-15T23:45:09.296Z",
          },
          {
            entryId: "t-mloe7wfb-mc9grw",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Directly attacking a dragon in its lair during a cave-in is high threat and high reward.",
            createdAtIso: "2026-02-15T23:45:10.631Z",
          },
          {
            entryId: "t-mloe7x5f-021ce6",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Fumble (-1 Effect).",
            createdAtIso: "2026-02-15T23:45:11.571Z",
          },
          {
            entryId: "t-mloe7zjx-urwx1q",
            kind: "storyteller",
            author: "Storyteller",
            text: "You raise your repeating crossbow, aiming for a vulnerable spot. However, a sudden tremor from the compromised ceiling causes your shot to go wide, striking a nearby rock formation instead. A cascade of loose stones tumbles down, narrowly missing you and creating a temporary dust cloud that obscures your vision. The dragon, momentarily startled by the falling debris, recovers its focus quickly. You must clear your line of sight and re-engage.",
            createdAtIso: "2026-02-15T23:45:14.685Z",
          },
          {
            entryId: "t-mloe9cmz-oabt83",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I could use the axe now. I go look for it",
            createdAtIso: "2026-02-15T23:46:18.299Z",
          },
          {
            entryId: "t-mloe9g3v-ambpnl",
            kind: "storyteller",
            author: "Storyteller",
            text: "The dust cloud, while thick, does not entirely obscure your immediate surroundings. You recall the axe being dislodged during the initial cave-in, likely near where you were standing. As you pivot to search, you feel the subtle shift of the unstable ground beneath your boots. The dragon, no longer startled, lets out a guttural sound, its looming shadow discernible even through the particulate haze.\nYou can attempt to locate your axe within the obscured area, or you can choose a different immediate action.",
            createdAtIso: "2026-02-15T23:46:22.795Z",
          },
          {
            entryId: "t-mloeb6v5-cj8p7s",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I look for the axe",
            createdAtIso: "2026-02-15T23:47:44.129Z",
          },
          {
            entryId: "t-mloeb7mt-tqg6oz",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Searching for a critical tool in a dangerous, unstable environment with a dragon nearby presents immediate threat and uncertainty.",
            createdAtIso: "2026-02-15T23:47:45.125Z",
          },
          {
            entryId: "t-mloeb89y-5p0f17",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Fumble (-1 Effect).",
            createdAtIso: "2026-02-15T23:47:45.958Z",
          },
          {
            entryId: "t-mloebaq4-7wcxjv",
            kind: "storyteller",
            author: "Storyteller",
            text: "Your hand sweeps across the rubble-strewn floor, but instead of the cold steel of your axe, your fingers close around a jagged, razor-sharp shard of rock, slicing your palm. You wince, the pain a sharp counterpoint to the dragon's low growl, which seems to vibrate through the cavern floor. The dust begins to settle, revealing the immense, scaly form of the beast, its head now turning slowly in your general direction.\nYou can press on with your search despite the injury, or you can choose to engage the dragon without your axe.",
            createdAtIso: "2026-02-15T23:47:49.132Z",
          },
          {
            entryId: "t-mloeczel-3cj9x9",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I attach a dynamite stick to the next bolt and take good aim for when the dragon comes for another attack. I want to shoot it into its open mouth.",
            createdAtIso: "2026-02-15T23:49:07.773Z",
          },
          {
            entryId: "t-mloed06l-h9g61i",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, play an Outcome card. Directly engaging a dragon with a prepared explosive is high-stakes threat and uncertainty.",
            createdAtIso: "2026-02-15T23:49:08.781Z",
          },
          {
            entryId: "t-mloed1dz-iz6bw1",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "played Outcome card: Success (+2 Effect).",
            createdAtIso: "2026-02-15T23:49:10.343Z",
          },
          {
            entryId: "t-mloed3za-vza6kk",
            kind: "storyteller",
            author: "Storyteller",
            text: "You swiftly affix the dynamite to a crossbow bolt, your injured hand a minor distraction compared to the colossal beast before you. As the dragon opens its maw, a low rumble preceding its fiery breath, you unleash the bolt with precision. The projectile, a flickering fuse trailing behind it, flies true, disappearing into the dark cavern of its throat. A muffled *thump* resonates, followed by a sudden, violent spasm from the dragon. It rears back, a pained roar shaking the cavern. The creature is clearly wounded, its attack momentarily disrupted.\nYou have a brief window to act while the dragon is disoriented.",
            createdAtIso: "2026-02-15T23:49:13.702Z",
          },
          {
            entryId: "t-mloed4m5-7v8xu9",
            kind: "storyteller",
            author: "Storyteller",
            text: "Ralph Stoneshard, give one final finishing move that secures the objective. Describe how the scene closes, then we will transition.",
            createdAtIso: "2026-02-15T23:49:14.525Z",
          },
          {
            entryId: "t-mloefgjx-bx9ojn",
            kind: "player",
            author: "Ralph Stoneshard",
            text: "I finally see the ancient axe in the pile of coins at my feet. I grab it as I run to finish the dragon. With it's head on the ground, I run right at it and slash it deep into its eye.",
            createdAtIso: "2026-02-15T23:51:03.309Z",
          },
          {
            entryId: "t-mloefhlh-12x3uu",
            kind: "storyteller",
            author: "Storyteller",
            text: "You spy your ancient axe amidst the glittering hoard. With a surge of adrenaline, you snatch it up, the familiar weight a comfort in your hand. The dragon, still reeling from the explosive, thrashes, its massive head momentarily pinned to the ground. You charge, axe raised, and with a grunt born of fury and desperation, you plunge the blade deep into its exposed eye. The beast lets out a final, earth-shattering shriek that echoes through the cavern before its immense body goes still.\nYou have slain the beast. What do you do now?",
            createdAtIso: "2026-02-15T23:51:04.661Z",
          },
          {
            entryId: "t-mloefit1-4is15j",
            kind: "system",
            author: "System",
            text: "Scene ended. Choose whether to continue this session with a new scene or end the session now.",
            createdAtIso: "2026-02-15T23:51:06.229Z",
          },
          {
            entryId: "t-mloefvgc-7mx1r4",
            kind: "system",
            author: "System",
            text: "Transition vote selected: End Session.",
            createdAtIso: "2026-02-15T23:51:22.620Z",
          },
          {
            entryId: "t-mloefvge-tj2wgr",
            kind: "system",
            author: "System",
            text: "Session ended by vote after closing the current scene.",
            createdAtIso: "2026-02-15T23:51:22.622Z",
          },
        ],
        scene: {
          sceneId: "scene-mlod7wz1-t7glns",
          imagePending: false,
          closingImagePending: false,
          mode: "high_tension",
          tension: 98,
          introProse:
            "The rumble has ceased, replaced by a suffocating silence. Dust motes dance in the faint light filtering through newly formed cracks above.  The air grows thick with the scent of brimstone and something ancient and reptilian.  You are Ralph Stoneshard, and the mountain has just become your tombâ€¦ or your forge.",
          orientationBullets: [
            "Cave-in sealing your exit.",
            "Dragon's lair ahead.",
            "Limited visibility.",
            "Stale, sulfurous air.",
          ],
          closingImageUrl: "/scenes/defeating-a-dragon.png",
          imageUrl: "/scenes/a-lone-adventurer-among-treasure.png",
          closingProse:
            "You spy your ancient axe amidst the glittering hoard. With a surge of adrenaline, you snatch it up, the familiar weight a comfort in your hand. The dragon, still reeling from the explosive, thrashes, its massive head momentarily pinned to the ground. You charge, axe raised, and with a grunt born of fury and desperation, you plunge the blade deep into its exposed eye. The beast lets out a final, earth-shattering shriek that echoes through the cavern before its immense body goes still. You have slain the beast. What do you do now?",
          summary:
            "Ralph Stoneshard, facing a subterranean dragon, successfully detonated dynamite within the beast's maw, causing significant injury and disorientation. This action, however, triggered a secondary cave-in, further complicating the escape. The dragon is wounded but enraged, and the environment is now more perilous.",
        },
      }}
      characterPortraitsByName={{
        "ralph stoneshard": {
          characterNameKey: "ralph stoneshard",
          characterName: "Ralph Stoneshard",
          imageUrl: "/profiles/ralph-stoneshard.png",
          status: "ready",
          updatedAtIso: "2026-02-15T23:16:39.266Z",
        },
      }}
      /* characterPortraitsByName={SAMPLE_PORTRAITS} */
      className="stack gap-4"
    />
  );
};
