import { z } from "zod";

export const assetBaseSlugs = [
  "medieval_gambeson",
  "medieval_chainmail",
  "medieval_plate_armor",
  "medieval_buckler",
  "medieval_kite-shield",
  "medieval_dagger",
  "medieval_hand_axe",
  "medieval_longsword",
  "medieval_zweihandler",
  "medieval_great_axe",
  "medieval_war_hammer",
  "medieval_mace",
  "medieval_morningstar",
  "medieval_staff",
  "medieval_spear",
  "medieval_billhook",
  "medieval_hunting_bow",
  "medieval_crossbow",
  "medieval_hand_cannon",
  "medieval_riding_horse",
  "medieval_wagon",
  "medieval_grappling_hook",
  "medieval_lockpick_set",
  "medieval_bandages",
  "medieval_healing_salve",
  "medieval_herbal_remedy",
  "medieval_prayer_book",
  "medieval_mead",
  "medieval_grenade",
  "medieval_lantern",
  "medieval_torch",
  "medieval_cannon",
  "medieval_rations",
  "medieval_pouch",
  "medieval_chest",
  "medieval_letter",
  "medieval_poison",
  "medieval_key",
  "medieval_trap",
  "medieval_tools",
  "medieval_digging",
  "medieval_ore",
  "medieval_stone",
  "medieval_wood",
  "medieval_iron",
  "medieval_silver",
  "medieval_gold",
  "base_light_weapon",
  "base_heavy_weapon",
  "base_reach_weapon",
  "base_spread_weapon",
  "base_throwable_weapon",
  "base_precision_weapon",
  "base_repeating_weapon",
  "base_artillery_weapon",
  "base_light_armor",
  "base_heavy_armor",
  "base_shield",
  "base_healing",
  "base_comfort",
  "base_surge",
  "base_tools",
  "base_light",
  "base_vehicle",
  "base_package",
  "base_document",
  "base_valuables",
  "base_key",
  "base_resources",
] as const;
export type AssetBaseSlug = (typeof assetBaseSlugs)[number];
export const assetBaseSlugSchema = z.enum(assetBaseSlugs);

export const assetModifierSlugs = [
  "base_fast",
  "base_empowered",
  "base_wide",
  "base_burning",
  "base_freezing",
  "base_insulating",
  "base_irritating",
  "base_penetrating",
  "base_fragile",
  "base_permanent",
  "base_hidden",
  "base_annoying",
  "base_dangerous",
  "base_pushing",
  "base_pulling",
  "base_area",
] as const;
export type AssetModifierSlug = (typeof assetModifierSlugs)[number];
export const assetModifierSlugSchema = z.enum(assetModifierSlugs);

export type AssetBaseGroupLabel = "Asset Base" | "Asset Medieval";

export const defaultAssetBaseSlug: AssetBaseSlug = "base_package";

export const assetBaseCatalog = [
  { slug: "medieval_gambeson", title: "Gambeson", group: "Asset Medieval" },
  { slug: "medieval_chainmail", title: "Chainmail", group: "Asset Medieval" },
  { slug: "medieval_plate_armor", title: "Plate Armor", group: "Asset Medieval" },
  { slug: "medieval_buckler", title: "Buckler", group: "Asset Medieval" },
  { slug: "medieval_kite-shield", title: "Kite Shield", group: "Asset Medieval" },
  { slug: "medieval_dagger", title: "Dagger", group: "Asset Medieval" },
  { slug: "medieval_hand_axe", title: "Hand Axe", group: "Asset Medieval" },
  { slug: "medieval_longsword", title: "Longsword", group: "Asset Medieval" },
  { slug: "medieval_zweihandler", title: "Zweih\u00e4nder", group: "Asset Medieval" },
  { slug: "medieval_great_axe", title: "Greataxe", group: "Asset Medieval" },
  { slug: "medieval_war_hammer", title: "War Hammer", group: "Asset Medieval" },
  { slug: "medieval_mace", title: "Mace", group: "Asset Medieval" },
  { slug: "medieval_morningstar", title: "Morningstar", group: "Asset Medieval" },
  { slug: "medieval_staff", title: "Staff", group: "Asset Medieval" },
  { slug: "medieval_spear", title: "Spear", group: "Asset Medieval" },
  { slug: "medieval_billhook", title: "Billhook", group: "Asset Medieval" },
  { slug: "medieval_hunting_bow", title: "Hunting Bow", group: "Asset Medieval" },
  { slug: "medieval_crossbow", title: "Crossbow", group: "Asset Medieval" },
  { slug: "medieval_hand_cannon", title: "Hand-Cannon", group: "Asset Medieval" },
  { slug: "medieval_riding_horse", title: "Riding Horse", group: "Asset Medieval" },
  { slug: "medieval_wagon", title: "Horse-Drawn Wagon", group: "Asset Medieval" },
  { slug: "medieval_grappling_hook", title: "Grappling Hook and Rope", group: "Asset Medieval" },
  { slug: "medieval_lockpick_set", title: "Lockpick Set", group: "Asset Medieval" },
  { slug: "medieval_bandages", title: "Bandages", group: "Asset Medieval" },
  { slug: "medieval_healing_salve", title: "Healing Salve", group: "Asset Medieval" },
  { slug: "medieval_herbal_remedy", title: "Herbal Remedy", group: "Asset Medieval" },
  { slug: "medieval_prayer_book", title: "Prayer Book", group: "Asset Medieval" },
  { slug: "medieval_mead", title: "Mead", group: "Asset Medieval" },
  { slug: "medieval_grenade", title: "Grenade", group: "Asset Medieval" },
  { slug: "medieval_lantern", title: "Lantern", group: "Asset Medieval" },
  { slug: "medieval_torch", title: "Torch", group: "Asset Medieval" },
  { slug: "medieval_cannon", title: "Cannon", group: "Asset Medieval" },
  { slug: "medieval_rations", title: "Rations", group: "Asset Medieval" },
  { slug: "medieval_pouch", title: "Pouch", group: "Asset Medieval" },
  { slug: "medieval_chest", title: "Chest", group: "Asset Medieval" },
  { slug: "medieval_letter", title: "Letter", group: "Asset Medieval" },
  { slug: "medieval_poison", title: "Poison", group: "Asset Medieval" },
  { slug: "medieval_key", title: "Key", group: "Asset Medieval" },
  { slug: "medieval_trap", title: "Trap", group: "Asset Medieval" },
  { slug: "medieval_tools", title: "Tools", group: "Asset Medieval" },
  { slug: "medieval_digging", title: "Digging tools", group: "Asset Medieval" },
  { slug: "medieval_ore", title: "Ore", group: "Asset Medieval" },
  { slug: "medieval_stone", title: "Stone", group: "Asset Medieval" },
  { slug: "medieval_wood", title: "Wood", group: "Asset Medieval" },
  { slug: "medieval_iron", title: "Iron", group: "Asset Medieval" },
  { slug: "medieval_silver", title: "Silver", group: "Asset Medieval" },
  { slug: "medieval_gold", title: "Gold", group: "Asset Medieval" },
  { slug: "base_light_weapon", title: "Light Weapon", group: "Asset Base" },
  { slug: "base_heavy_weapon", title: "Heavy Weapon", group: "Asset Base" },
  { slug: "base_reach_weapon", title: "Reach Weapon", group: "Asset Base" },
  { slug: "base_spread_weapon", title: "Spread Weapon", group: "Asset Base" },
  { slug: "base_throwable_weapon", title: "Throwable Weapon", group: "Asset Base" },
  { slug: "base_precision_weapon", title: "Precision Weapon", group: "Asset Base" },
  { slug: "base_repeating_weapon", title: "Repeating Weapon", group: "Asset Base" },
  { slug: "base_artillery_weapon", title: "Artillery Weapon", group: "Asset Base" },
  { slug: "base_light_armor", title: "Light Armor", group: "Asset Base" },
  { slug: "base_heavy_armor", title: "Heavy Armor", group: "Asset Base" },
  { slug: "base_shield", title: "Shield", group: "Asset Base" },
  { slug: "base_healing", title: "Healing", group: "Asset Base" },
  { slug: "base_comfort", title: "Comfort", group: "Asset Base" },
  { slug: "base_surge", title: "Surge", group: "Asset Base" },
  { slug: "base_tools", title: "Tools", group: "Asset Base" },
  { slug: "base_light", title: "Light", group: "Asset Base" },
  { slug: "base_vehicle", title: "Vehicle", group: "Asset Base" },
  { slug: "base_package", title: "Package", group: "Asset Base" },
  { slug: "base_document", title: "Document", group: "Asset Base" },
  { slug: "base_valuables", title: "Valuables", group: "Asset Base" },
  { slug: "base_key", title: "Key", group: "Asset Base" },
  { slug: "base_resources", title: "Resources", group: "Asset Base" },
] as const satisfies readonly {
  slug: AssetBaseSlug;
  title: string;
  group: AssetBaseGroupLabel;
}[];

export const assetBaseBaseCatalog = assetBaseCatalog.filter(
  (entry) => entry.group === "Asset Base",
);

export const assetBaseMedievalCatalog = assetBaseCatalog.filter(
  (entry) => entry.group === "Asset Medieval",
);

export const assetModifierCatalog = [
  { slug: "base_fast", title: "Fast" },
  { slug: "base_empowered", title: "Empowered" },
  { slug: "base_wide", title: "Wide" },
  { slug: "base_burning", title: "Burning" },
  { slug: "base_freezing", title: "Freezing" },
  { slug: "base_insulating", title: "Insulating" },
  { slug: "base_irritating", title: "Irritating" },
  { slug: "base_penetrating", title: "Penetrating" },
  { slug: "base_fragile", title: "Fragile" },
  { slug: "base_permanent", title: "Permanent" },
  { slug: "base_hidden", title: "Hidden" },
  { slug: "base_annoying", title: "Annoying" },
  { slug: "base_dangerous", title: "Dangerous" },
  { slug: "base_pushing", title: "Pushing" },
  { slug: "base_pulling", title: "Pulling" },
  { slug: "base_area", title: "Area" },
] as const satisfies readonly {
  slug: AssetModifierSlug;
  title: string;
}[];

