import { getActorBaseImageUri } from "../../data/actorCards";
import type {
  CardLibraryEntry,
  ShipActorInstance,
  ShipLocationInstance,
  SpaceshipScene,
} from "./spaceshipTypes";

const createPlayerLocation = (
  location: Omit<ShipLocationInstance, "lastTouchedOrder">,
  index: number,
): ShipLocationInstance => ({
  ...location,
  lastTouchedOrder: index + 1,
});

const createActor = (
  actor: Omit<ShipActorInstance, "lastTouchedOrder">,
  index: number,
): ShipActorInstance => ({
  ...actor,
  lastTouchedOrder: index + 1,
});

const playerShipLocations: ShipLocationInstance[] = [
  createPlayerLocation(
    {
      locationId: "player-docking-bay",
      title: "Docking Bay",
      locationType: "docking-bay",
      level: 1,
      row: "top",
      moduleLocationSlug: "docking-bay",
      summary: "Imperial shuttle still latched to the scarred lock.",
      status: "Boarding option held in reserve.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/docking-bay-63de54ac4b3c469379e9.png",
    },
    0,
  ),
  createPlayerLocation(
    {
      locationId: "player-reactor",
      title: "Reactor",
      locationType: "reactor",
      level: 2,
      row: "top",
      moduleLocationSlug: "reactor",
      summary: "Minimal output, one line feeding life support.",
      status: "1 PU online, fuel gone, overdrive tempting.",
      effects: [{ effectId: "reactor-distress", type: "distress", label: "Distress", detail: "Output feels one step down.", count: 1 }],
      energyTokens: [{ tokenId: "reactor-energy", label: "1", detail: "Active power", locationId: "player-reactor" }],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/reactor-99836c3e8add9c720018.png",
      energyCost: 1,
    },
    1,
  ),
  createPlayerLocation(
    {
      locationId: "player-engines",
      title: "Engines",
      locationType: "engine-room",
      level: 2,
      row: "top",
      moduleLocationSlug: "engines",
      summary: "Cold thrusters waiting for power and a real pilot.",
      status: "Unpowered, maneuvering only if fed.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/engine-room-e8d353054b6ec0d933a4.png",
      energyCost: 1,
    },
    2,
  ),
  createPlayerLocation(
    {
      locationId: "player-spin-drive",
      title: "Spin Drive",
      locationType: "spin-drive",
      level: 1,
      row: "top",
      moduleLocationSlug: "spin-drive",
      summary: "Five turns from escape, if the rings stay intact.",
      status: "Charging sequence stalled.",
      effects: [{ effectId: "spin-freezing", type: "freezing", label: "Freezing", detail: "Pressure outside the hull keeps climbing.", count: 1 }],
      energyTokens: [{ tokenId: "spin-energy", label: "1", detail: "Charge line", locationId: "player-spin-drive" }],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/spin-drive-0272c9d7519a20661052.png",
      energyCost: 1,
    },
    3,
  ),
  createPlayerLocation(
    {
      locationId: "player-weapon-station",
      title: "Weapon Station",
      locationType: "weapons-station",
      level: 1,
      row: "top",
      moduleLocationSlug: "weapon-station",
      summary: "One surviving laser array and a half-burned capacitor.",
      status: "Single shot lane only.",
      effects: [{ effectId: "weapon-distress", type: "distress", label: "Distress", detail: "Capacitor arc scarred the mount.", count: 1 }],
      energyTokens: [{ tokenId: "weapon-energy", label: "1", detail: "Laser feed", locationId: "player-weapon-station" }],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/weapons-station-436da3cb55bbcb0d221c.png",
      energyCost: 1,
    },
    4,
  ),
  createPlayerLocation(
    {
      locationId: "player-missile-bay",
      title: "Missile Bay",
      locationType: "missile-bay",
      level: 1,
      row: "top",
      moduleLocationSlug: "missile-bay",
      summary: "No missiles loaded, but enough scrap for one ugly shell.",
      status: "Manual loading only.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/missile-bay-97234afe5d3d668c403b.png",
    },
    5,
  ),
  createPlayerLocation(
    {
      locationId: "player-sealed-corridor",
      title: "Sealed Corridor",
      locationType: "sealed-corridor",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "sealed-corridor",
      summary: "Hard seals, scratch marks, and the promise of more rooms.",
      status: "Locked down until heavier tools arrive.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/elevator-0bad159122ccb9891981.png",
    },
    6,
  ),
  createPlayerLocation(
    {
      locationId: "player-crew-quarters",
      title: "Crew Quarters",
      locationType: "crew-quarters",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "crew-quarters",
      summary: "Eight bunks, one corpse, one missing key.",
      status: "Still unpressurized.",
      effects: [{ effectId: "quarters-freezing", type: "freezing", label: "Freezing", detail: "Vacuum frost lingers behind the hatch.", count: 1 }],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/crew-quarters-fb4b60ee93280b0a8dca.png",
    },
    7,
  ),
  createPlayerLocation(
    {
      locationId: "player-life-support",
      title: "Life Support",
      locationType: "life-support",
      level: 2,
      row: "bottom",
      moduleLocationSlug: "life-support",
      summary: "Pressure, heat, and water routing all bottleneck here.",
      status: "Barely breathable ship-wide.",
      effects: [],
      energyTokens: [{ tokenId: "life-support-energy", label: "1", detail: "Air loop", locationId: "player-life-support" }],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/life-support-7cc06593453ccad5dd9c.png",
      energyCost: 1,
    },
    8,
  ),
  createPlayerLocation(
    {
      locationId: "player-cockpit",
      title: "Cockpit",
      locationType: "cockpit",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "cockpit",
      summary: "Navigation cradle, evasive lane, and a broken orientation dial.",
      status: "Pilot station clear.",
      effects: [],
      energyTokens: [],
      actorTokens: [
        {
          tokenId: "pilot-token",
          label: "Pilot",
          imageUrl: getActorBaseImageUri("manipulator"),
          title: "Cockpit",
          subtitle: "Evasion ready",
          tone: "gold",
          locationId: "player-cockpit",
        },
      ],
      imageUrl: "/api/adventure-artifacts/cockpit-435a2f81c0be0c184b58.png",
    },
    9,
  ),
  createPlayerLocation(
    {
      locationId: "player-sensor-array",
      title: "Sensor Array",
      locationType: "sensor-array",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "sensor-array",
      summary: "Contact map, breach alarms, and a haunted lifesign feed.",
      status: "Calibration pending.",
      effects: [],
      energyTokens: [],
      actorTokens: [
        {
          tokenId: "seer-token",
          label: "Void-seer",
          imageUrl: getActorBaseImageUri("manipulator"),
          title: "Sensor Array",
          subtitle: "Surveying",
          tone: "cloth",
          locationId: "player-sensor-array",
        },
      ],
      imageUrl: "/api/adventure-artifacts/sensor-array-b8329e59ab1bed4cfeae.png",
      energyCost: 1,
    },
    10,
  ),
  createPlayerLocation(
    {
      locationId: "player-cargo-hold",
      title: "Cargo Hold",
      locationType: "cargo-hold",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "cargo-hold",
      summary: "Rations, scavenged parts, and nowhere near enough margin.",
      status: "Supply stack stable.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/cargo-hold-202afa0e160b9f892887.png",
    },
    11,
  ),
];

const pirateShipLocations: ShipLocationInstance[] = [
  createPlayerLocation(
    {
      locationId: "pirate-docking-bay",
      title: "Docking Bay",
      locationType: "docking-bay",
      level: 1,
      row: "top",
      moduleLocationSlug: "pirate-docking-bay",
      summary: "A stripped bay ready for looting runs, not comfort.",
      status: "Breaching hooks primed.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/docking-bay-63de54ac4b3c469379e9.png",
    },
    12,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-cargo-hold",
      title: "Cargo Hold",
      locationType: "cargo-hold",
      level: 1,
      row: "top",
      moduleLocationSlug: "pirate-cargo-hold",
      summary: "Loot cages and scorched crates rattle with every turn.",
      status: "Spoils unsecured.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/cargo-hold-202afa0e160b9f892887.png",
    },
    13,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-crew-quarters",
      title: "Crew Quarters",
      locationType: "crew-quarters",
      level: 1,
      row: "top",
      moduleLocationSlug: "pirate-crew-quarters",
      summary: "Skeleton crew, idle bunks, and bodies that stopped moving.",
      status: "Life signs low.",
      effects: [{ effectId: "pirate-quarters-distress", type: "distress", label: "Distress", detail: "Crew attrition everywhere.", count: 1 }],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/crew-quarters-fb4b60ee93280b0a8dca.png",
    },
    14,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-spin-drive",
      title: "Spin Drive",
      locationType: "spin-drive",
      level: 1,
      row: "top",
      moduleLocationSlug: "pirate-spin-drive",
      summary: "Their escape route stays one powering cycle away.",
      status: "Charging under pressure.",
      effects: [],
      energyTokens: [{ tokenId: "pirate-spin-energy", label: "1", detail: "Charge line", locationId: "pirate-spin-drive" }],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/spin-drive-0272c9d7519a20661052.png",
      energyCost: 1,
    },
    15,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-engine-room",
      title: "Engine Room",
      locationType: "engine-room",
      level: 1,
      row: "top",
      moduleLocationSlug: "pirate-engine-room",
      summary: "Damaged engines still bully the transport through the rocks.",
      status: "Running hot in the asteroid field.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/engine-room-e8d353054b6ec0d933a4.png",
      energyCost: 1,
    },
    16,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-reactor",
      title: "Reactor",
      locationType: "reactor",
      level: 2,
      row: "bottom",
      moduleLocationSlug: "pirate-reactor",
      summary: "Damaged enough that the raiders alternate weapon feeds.",
      status: "Output unstable.",
      effects: [{ effectId: "pirate-reactor-distress", type: "distress", label: "Distress", detail: "Alternating power routes.", count: 1 }],
      energyTokens: [{ tokenId: "pirate-reactor-energy", label: "2", detail: "Core feed", locationId: "pirate-reactor" }],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/reactor-99836c3e8add9c720018.png",
      energyCost: 2,
    },
    17,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-shield-generator",
      title: "Shield Generator",
      locationType: "shield-generator",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "pirate-shield-generator",
      summary: "A thin energy skin soaking glancing laser fire.",
      status: "Shield shimmer visible.",
      effects: [],
      energyTokens: [{ tokenId: "pirate-shield-energy", label: "1", detail: "Barrier", locationId: "pirate-shield-generator" }],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/shield-generator-4cba0cdd2221c9828238.png",
      energyCost: 2,
    },
    18,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-weapons-station",
      title: "Weapons Station",
      locationType: "weapons-station",
      level: 2,
      row: "bottom",
      moduleLocationSlug: "pirate-weapons-station",
      summary: "Disruptor and laser array chained into one predatory fire lane.",
      status: "Alternating weapon feed.",
      effects: [],
      energyTokens: [{ tokenId: "pirate-weapons-energy", label: "1", detail: "Laser lane", locationId: "pirate-weapons-station" }],
      actorTokens: [
        {
          tokenId: "raider-gunner-token",
          label: "Raider",
          imageUrl: getActorBaseImageUri("animal_red"),
          title: "Weapons Station",
          subtitle: "Target lock",
          tone: "fire",
          locationId: "pirate-weapons-station",
        },
      ],
      imageUrl: "/api/adventure-artifacts/weapons-station-436da3cb55bbcb0d221c.png",
      energyCost: 1,
    },
    19,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-cockpit",
      title: "Cockpit",
      locationType: "cockpit",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "pirate-cockpit",
      summary: "A stolen corvette bridge driven on appetite and spite.",
      status: "Asteroid weave engaged.",
      effects: [],
      energyTokens: [],
      actorTokens: [
        {
          tokenId: "raider-pilot-token",
          label: "Pilot",
          imageUrl: getActorBaseImageUri("animal_red"),
          title: "Cockpit",
          subtitle: "Weaving",
          tone: "blood",
          locationId: "pirate-cockpit",
        },
      ],
      imageUrl: "/api/adventure-artifacts/cockpit-435a2f81c0be0c184b58.png",
    },
    20,
  ),
];

const playerActors: ShipActorInstance[] = [
  createActor(
    {
      actorId: "actor-machinist",
      name: "Machinist-Priest",
      callout: "Reactor rites and patchwork miracles.",
      baseLayerSlug: "cog",
      tacticalRoleSlug: "champion",
      token: {
        tokenId: "actor-machinist-token",
        label: "Machinist",
        imageUrl: getActorBaseImageUri("cog"),
        title: "Reactor",
        subtitle: "Routing power",
        tone: "gold",
      },
      injuryCount: 1,
      distressCount: 0,
    },
    0,
  ),
  createActor(
    {
      actorId: "actor-veteran",
      name: "Augmented Veteran",
      callout: "Keeps the corridor sealed and the crew upright.",
      baseLayerSlug: "bruiser_red",
      tacticalRoleSlug: "brute",
      token: {
        tokenId: "actor-veteran-token",
        label: "Veteran",
        imageUrl: getActorBaseImageUri("bruiser_red"),
        title: "Sealed Corridor",
        subtitle: "Holding line",
        tone: "fire",
      },
      injuryCount: 2,
      distressCount: 1,
    },
    1,
  ),
  createActor(
    {
      actorId: "actor-seer",
      name: "Void-seer",
      callout: "Surveys the black and counts the seconds to jump.",
      baseLayerSlug: "manipulator",
      tacticalRoleSlug: "ranger",
      token: {
        tokenId: "actor-seer-strip-token",
        label: "Void-seer",
        imageUrl: getActorBaseImageUri("manipulator"),
        title: "Sensor Array",
        subtitle: "Reading echoes",
        tone: "cloth",
      },
      injuryCount: 0,
      distressCount: 2,
    },
    2,
  ),
  createActor(
    {
      actorId: "actor-medic",
      name: "Synthetic Medic",
      callout: "Keeping the air and blood in the same places.",
      baseLayerSlug: "healer",
      tacticalRoleSlug: "ranger",
      token: {
        tokenId: "actor-medic-token",
        label: "Medic",
        imageUrl: getActorBaseImageUri("healer"),
        title: "Life Support",
        subtitle: "Repressurizing",
        tone: "monster",
      },
      injuryCount: 1,
      distressCount: 1,
    },
    3,
  ),
];

const pirateActors: ShipActorInstance[] = [
  createActor(
    {
      actorId: "actor-raider-gunner",
      name: "Raider Gunner",
      callout: "Alternates disruptor bursts with the laser lane.",
      baseLayerSlug: "animal_red",
      tacticalRoleSlug: "minion",
      token: {
        tokenId: "actor-raider-gunner-strip-token",
        label: "Gunner",
        imageUrl: getActorBaseImageUri("animal_red"),
        title: "Weapons Station",
        subtitle: "Harassing fire",
        tone: "blood",
      },
      injuryCount: 0,
      distressCount: 2,
    },
    0,
  ),
  createActor(
    {
      actorId: "actor-raider-pilot",
      name: "Raider Pilot",
      callout: "Cuts through the asteroid field on stolen instincts.",
      baseLayerSlug: "animal_red",
      tacticalRoleSlug: "minion",
      token: {
        tokenId: "actor-raider-pilot-strip-token",
        label: "Pilot",
        imageUrl: getActorBaseImageUri("animal_red"),
        title: "Cockpit",
        subtitle: "Asteroid weave",
        tone: "fire",
      },
      injuryCount: 1,
      distressCount: 1,
    },
    1,
  ),
];

const cardLibrary: CardLibraryEntry[] = [
  {
    entryId: "card-player-cockpit",
    type: "location",
    title: "Cockpit",
    category: "Player Ship",
    summary: "Movement, evasive maneuvers, and the best window into the chaos.",
    badge: "Location",
  },
  {
    entryId: "card-player-reactor",
    type: "location",
    title: "Reactor",
    category: "Player Ship",
    summary: "Power routing, overdrive, and the whole ship’s pacing lever.",
    badge: "Location",
  },
  {
    entryId: "card-player-distress",
    type: "effect",
    title: "Distress",
    category: "Effect",
    summary: "Damage that knocks a room one level lower per card.",
    badge: "Effect",
  },
  {
    entryId: "card-player-freezing",
    type: "effect",
    title: "Freezing",
    category: "Effect",
    summary: "Decompression marker for hull breaches and cold-soaked rooms.",
    badge: "Effect",
  },
  {
    entryId: "card-energy-token",
    type: "token",
    title: "Energy Token",
    category: "Token",
    summary: "Shows which system is currently being fed.",
    badge: "Token",
  },
  {
    entryId: "card-raider-gunner",
    type: "actor",
    title: "Raider Gunner",
    category: "Enemy Crew",
    summary: "Placeholder crew card for the pirate weapons lane.",
    badge: "Actor",
  },
];

export const spaceshipScene: SpaceshipScene = {
  sceneId: "scene-exiles-ship-prototype",
  title: "Exiles Ship Combat Mockup",
  subtitle:
    "Low-fi tactical board for ship systems, damage pressure, crew positions, and future drag layers.",
  panes: [
    {
      paneId: "pane-player",
      title: "Exiles Corvette",
      subtitle: "Derelict corvette held together by ritual, frost, and stubborn crew.",
      faction: "Crew",
      emphasis: "player",
      locations: playerShipLocations,
      actors: playerActors,
    },
    {
      paneId: "pane-pirate",
      title: "Xithrax Raider",
      subtitle: "Stolen corvette pushing a transport through the rocks.",
      faction: "Pirates",
      emphasis: "enemy",
      locations: pirateShipLocations,
      actors: pirateActors,
    },
  ],
  overlay: {
    open: false,
  },
  selection: {
    selectedEntryIds: [],
  },
  zBands: {
    cards: [
      ...playerShipLocations.map((location) => location.locationId),
      ...pirateShipLocations.map((location) => location.locationId),
    ],
    tokens: [
      ...playerShipLocations.flatMap((location) =>
        location.actorTokens.map((token) => token.tokenId),
      ),
      ...pirateShipLocations.flatMap((location) =>
        location.actorTokens.map((token) => token.tokenId),
      ),
    ],
  },
  cardLibrary,
};
