import { getActorBaseImageUri } from "../../../data/actorCards";
import { createActor, createPlayerLocation } from "./content";
import type {
  ShipActorInstance,
  ShipLocationInstance,
} from "./types";

export const pirateShipLocations: ShipLocationInstance[] = [
  createPlayerLocation(
    {
      locationId: "pirate-docking-bay",
      title: "Docking Bay",
      locationType: "docking-bay",
      level: 1,
      row: "top",
      moduleLocationSlug: "pirate-docking-bay",
      summary: "A stripped bay ready for looting runs, not comfort.",
      status: "Breaching hooks primed.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/docking-bay-63de54ac4b3c469379e9.png",
    },
    12,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-cargo-hold",
      title: "Cargo Hold",
      locationType: "cargo-hold",
      level: 1,
      row: "top",
      moduleLocationSlug: "pirate-cargo-hold",
      summary: "Loot cages and scorched crates rattle with every turn.",
      status: "Spoils unsecured.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/cargo-hold-202afa0e160b9f892887.png",
    },
    13,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-crew-quarters",
      title: "Crew Quarters",
      locationType: "crew-quarters",
      level: 1,
      row: "top",
      moduleLocationSlug: "pirate-crew-quarters",
      summary: "Skeleton crew, idle bunks, and bodies that stopped moving.",
      status: "Life signs low.",
      effects: [
        {
          effectId: "pirate-quarters-distress",
          type: "distress",
          label: "Distress",
          detail: "Crew attrition everywhere.",
          count: 1,
        },
      ],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/crew-quarters-fb4b60ee93280b0a8dca.png",
    },
    14,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-spin-drive",
      title: "Spin Drive",
      locationType: "spin-drive",
      level: 1,
      row: "top",
      moduleLocationSlug: "pirate-spin-drive",
      summary: "Their escape route stays one powering cycle away.",
      status: "Charging under pressure.",
      effects: [],
      energyTokens: [
        {
          tokenId: "pirate-spin-energy",
          label: "1",
          detail: "Charge line",
          locationId: "pirate-spin-drive",
        },
      ],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/spin-drive-0272c9d7519a20661052.png",
      energyCost: 1,
    },
    15,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-engine-room",
      title: "Engine Room",
      locationType: "engine-room",
      level: 1,
      row: "top",
      moduleLocationSlug: "pirate-engine-room",
      summary: "Damaged engines still bully the transport through the rocks.",
      status: "Running hot in the asteroid field.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/engine-room-e8d353054b6ec0d933a4.png",
      energyCost: 1,
    },
    16,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-reactor",
      title: "Reactor",
      locationType: "reactor",
      level: 2,
      row: "bottom",
      moduleLocationSlug: "pirate-reactor",
      summary: "Damaged enough that the raiders alternate weapon feeds.",
      status: "Output unstable.",
      effects: [
        {
          effectId: "pirate-reactor-distress",
          type: "distress",
          label: "Distress",
          detail: "Alternating power routes.",
          count: 1,
        },
      ],
      energyTokens: [
        {
          tokenId: "pirate-reactor-energy",
          label: "2",
          detail: "Core feed",
          locationId: "pirate-reactor",
        },
      ],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/reactor-99836c3e8add9c720018.png",
      energyCost: 2,
    },
    17,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-shield-generator",
      title: "Shield Generator",
      locationType: "shield-generator",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "pirate-shield-generator",
      summary: "A thin energy skin soaking glancing laser fire.",
      status: "Shield shimmer visible.",
      effects: [],
      energyTokens: [
        {
          tokenId: "pirate-shield-energy",
          label: "1",
          detail: "Barrier",
          locationId: "pirate-shield-generator",
        },
      ],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/shield-generator-4cba0cdd2221c9828238.png",
      energyCost: 2,
    },
    18,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-weapons-station",
      title: "Weapons Station",
      locationType: "weapons-station",
      level: 2,
      row: "bottom",
      moduleLocationSlug: "pirate-weapons-station",
      summary: "Disruptor and laser array chained into one predatory fire lane.",
      status: "Alternating weapon feed.",
      effects: [],
      energyTokens: [
        {
          tokenId: "pirate-weapons-energy",
          label: "1",
          detail: "Spent weapon lane",
          locationId: "pirate-weapons-station",
          state: "spent",
        },
      ],
      actorTokens: [
        {
          tokenId: "raider-gunner-token",
          label: "Raider",
          imageUrl: getActorBaseImageUri("animal_red"),
          title: "Weapons Station",
          subtitle: "Target lock",
          tone: "fire",
          locationId: "pirate-weapons-station",
        },
      ],
      imageUrl: "/api/adventure-artifacts/weapons-station-436da3cb55bbcb0d221c.png",
      energyCost: 1,
    },
    19,
  ),
  createPlayerLocation(
    {
      locationId: "pirate-cockpit",
      title: "Cockpit",
      locationType: "cockpit",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "pirate-cockpit",
      summary: "A stolen corvette bridge driven on appetite and spite.",
      status: "Asteroid weave engaged.",
      effects: [],
      energyTokens: [],
      actorTokens: [
        {
          tokenId: "raider-pilot-token",
          label: "Pilot",
          imageUrl: getActorBaseImageUri("animal_red"),
          title: "Cockpit",
          subtitle: "Weaving",
          tone: "blood",
          locationId: "pirate-cockpit",
        },
      ],
      imageUrl: "/api/adventure-artifacts/cockpit-435a2f81c0be0c184b58.png",
    },
    20,
  ),
];

export const pirateActors: ShipActorInstance[] = [
  createActor(
    {
      actorId: "actor-raider-gunner",
      name: "Raider Gunner",
      callout: "Alternates disruptor bursts with the laser lane.",
      baseLayerSlug: "animal_red",
      tacticalRoleSlug: "minion",
      token: {
        tokenId: "actor-raider-gunner-strip-token",
        label: "Gunner",
        imageUrl: getActorBaseImageUri("animal_red"),
        title: "Weapons Station",
        subtitle: "Harassing fire",
        tone: "blood",
      },
      injuryCount: 0,
      distressCount: 2,
    },
    0,
  ),
  createActor(
    {
      actorId: "actor-raider-pilot",
      name: "Raider Pilot",
      callout: "Cuts through the asteroid field on stolen instincts.",
      baseLayerSlug: "animal_red",
      tacticalRoleSlug: "minion",
      token: {
        tokenId: "actor-raider-pilot-strip-token",
        label: "Pilot",
        imageUrl: getActorBaseImageUri("animal_red"),
        title: "Cockpit",
        subtitle: "Asteroid weave",
        tone: "fire",
      },
      injuryCount: 1,
      distressCount: 1,
    },
    1,
  ),
];

