import {
  createActor,
  createPlayerLocation,
  exilesActorCards,
  exilesActorTokens,
} from "./content";
import type {
  ShipActorInstance,
  ShipLocationInstance,
} from "./types";

export const playerShipLocations: ShipLocationInstance[] = [
  createPlayerLocation(
    {
      locationId: "player-docking-bay",
      title: "Docking Bay",
      locationType: "docking-bay",
      level: 1,
      row: "top",
      moduleLocationSlug: "docking-bay",
      summary: "Imperial shuttle still latched to the scarred lock.",
      status: "Boarding option held in reserve.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/docking-bay-63de54ac4b3c469379e9.png",
    },
    0,
  ),
  createPlayerLocation(
    {
      locationId: "player-reactor",
      title: "Reactor",
      locationType: "reactor",
      level: 2,
      row: "top",
      moduleLocationSlug: "reactor",
      summary: "Minimal output, one line feeding life support.",
      status: "1 PU online, fuel gone, overdrive tempting.",
      effects: [
        {
          effectId: "reactor-distress",
          type: "distress",
          label: "Distress",
          detail: "Output feels one step down.",
          count: 1,
        },
      ],
      energyTokens: [
        {
          tokenId: "reactor-energy",
          label: "1",
          detail: "Active power",
          locationId: "player-reactor",
        },
      ],
      actorTokens: [exilesActorTokens.machinist],
      imageUrl: "/api/adventure-artifacts/reactor-99836c3e8add9c720018.png",
      energyCost: 1,
    },
    1,
  ),
  createPlayerLocation(
    {
      locationId: "player-engines",
      title: "Engines",
      locationType: "engine-room",
      level: 2,
      row: "top",
      moduleLocationSlug: "engines",
      summary: "Cold thrusters waiting for power and a real pilot.",
      status: "Unpowered, maneuvering only if fed.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/engine-room-e8d353054b6ec0d933a4.png",
      energyCost: 1,
    },
    2,
  ),
  createPlayerLocation(
    {
      locationId: "player-spin-drive",
      title: "Spin Drive",
      locationType: "spin-drive",
      level: 1,
      row: "top",
      moduleLocationSlug: "spin-drive",
      summary: "Five turns from escape, if the rings stay intact.",
      status: "Charging sequence stalled.",
      effects: [
        {
          effectId: "spin-freezing",
          type: "freezing",
          label: "Freezing",
          detail: "Pressure outside the hull keeps climbing.",
          count: 1,
        },
      ],
      energyTokens: [
        {
          tokenId: "spin-energy",
          label: "1",
          detail: "Charge line",
          locationId: "player-spin-drive",
        },
      ],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/spin-drive-0272c9d7519a20661052.png",
      energyCost: 1,
    },
    3,
  ),
  createPlayerLocation(
    {
      locationId: "player-weapon-station",
      title: "Weapon Station",
      locationType: "weapons-station",
      level: 1,
      row: "top",
      moduleLocationSlug: "weapon-station",
      summary: "One surviving laser array and a half-burned capacitor.",
      status: "Single shot lane only.",
      effects: [
        {
          effectId: "weapon-distress",
          type: "distress",
          label: "Distress",
          detail: "Capacitor arc scarred the mount.",
          count: 1,
        },
      ],
      energyTokens: [
        {
          tokenId: "weapon-energy",
          label: "1",
          detail: "Spent laser feed locked until End of Round",
          locationId: "player-weapon-station",
          state: "spent",
        },
      ],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/weapons-station-436da3cb55bbcb0d221c.png",
      energyCost: 1,
    },
    4,
  ),
  createPlayerLocation(
    {
      locationId: "player-missile-bay",
      title: "Missile Bay",
      locationType: "missile-bay",
      level: 1,
      row: "top",
      moduleLocationSlug: "missile-bay",
      summary: "No missiles loaded, but enough scrap for one ugly shell.",
      status: "Manual loading only.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/missile-bay-97234afe5d3d668c403b.png",
    },
    5,
  ),
  createPlayerLocation(
    {
      locationId: "player-sealed-corridor",
      title: "Sealed Corridor",
      locationType: "sealed-corridor",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "sealed-corridor",
      summary: "Hard seals, scratch marks, and the promise of more rooms.",
      status: "Locked down until heavier tools arrive.",
      effects: [],
      energyTokens: [],
      actorTokens: [exilesActorTokens.veteran],
      imageUrl: "/api/adventure-artifacts/elevator-0bad159122ccb9891981.png",
    },
    6,
  ),
  createPlayerLocation(
    {
      locationId: "player-crew-quarters",
      title: "Crew Quarters",
      locationType: "crew-quarters",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "crew-quarters",
      summary: "Eight bunks, one corpse, one missing key.",
      status: "Still unpressurized.",
      effects: [
        {
          effectId: "quarters-freezing",
          type: "freezing",
          label: "Freezing",
          detail: "Vacuum frost lingers behind the hatch.",
          count: 1,
        },
      ],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/crew-quarters-fb4b60ee93280b0a8dca.png",
    },
    7,
  ),
  createPlayerLocation(
    {
      locationId: "player-life-support",
      title: "Life Support",
      locationType: "life-support",
      level: 2,
      row: "bottom",
      moduleLocationSlug: "life-support",
      summary: "Pressure, heat, and water routing all bottleneck here.",
      status: "Barely breathable ship-wide.",
      effects: [],
      energyTokens: [
        {
          tokenId: "life-support-energy",
          label: "1",
          detail: "Air loop",
          locationId: "player-life-support",
        },
      ],
      actorTokens: [exilesActorTokens.medic],
      imageUrl: "/api/adventure-artifacts/life-support-7cc06593453ccad5dd9c.png",
      energyCost: 1,
    },
    8,
  ),
  createPlayerLocation(
    {
      locationId: "player-cockpit",
      title: "Cockpit",
      locationType: "cockpit",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "cockpit",
      summary: "Navigation cradle, evasive lane, and a broken orientation dial.",
      status: "Pilot station clear.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/cockpit-435a2f81c0be0c184b58.png",
    },
    9,
  ),
  createPlayerLocation(
    {
      locationId: "player-sensor-array",
      title: "Sensor Array",
      locationType: "sensor-array",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "sensor-array",
      summary: "Contact map, breach alarms, and a haunted lifesign feed.",
      status: "Calibration pending.",
      effects: [],
      energyTokens: [],
      actorTokens: [exilesActorTokens.seer],
      imageUrl: "/api/adventure-artifacts/sensor-array-b8329e59ab1bed4cfeae.png",
      energyCost: 1,
    },
    10,
  ),
  createPlayerLocation(
    {
      locationId: "player-cargo-hold",
      title: "Cargo Hold",
      locationType: "cargo-hold",
      level: 1,
      row: "bottom",
      moduleLocationSlug: "cargo-hold",
      summary: "Rations, scavenged parts, and nowhere near enough margin.",
      status: "Supply stack stable.",
      effects: [],
      energyTokens: [],
      actorTokens: [],
      imageUrl: "/api/adventure-artifacts/cargo-hold-202afa0e160b9f892887.png",
    },
    11,
  ),
];

export const playerActors: ShipActorInstance[] = [
  createActor(
    {
      actorId: "actor-machinist",
      name: "Machinist-Priest",
      callout: "Reactor rites and patchwork miracles.",
      baseLayerSlug: "cog",
      tacticalRoleSlug: "champion",
      customCard: exilesActorCards.machinistPriestHeretic,
      token: {
        tokenId: "actor-machinist-token",
        label: "Machinist",
        imageUrl: exilesActorCards.machinistPriestHeretic.imageUrl,
        title: "Reactor",
        subtitle: "Routing power",
        tone: "gold",
      },
      injuryCount: 1,
      distressCount: 0,
    },
    0,
  ),
  createActor(
    {
      actorId: "actor-veteran",
      name: "Augmented Veteran",
      callout: "Keeps the corridor sealed and the crew upright.",
      baseLayerSlug: "bruiser_red",
      tacticalRoleSlug: "brute",
      customCard: exilesActorCards.augmentedVeteran,
      token: {
        tokenId: "actor-veteran-token",
        label: "Veteran",
        imageUrl: exilesActorCards.augmentedVeteran.imageUrl,
        title: "Sealed Corridor",
        subtitle: "Holding line",
        tone: "fire",
      },
      injuryCount: 2,
      distressCount: 1,
    },
    1,
  ),
  createActor(
    {
      actorId: "actor-seer",
      name: "Void-seer",
      callout: "Surveys the black and counts the seconds to jump.",
      baseLayerSlug: "manipulator",
      tacticalRoleSlug: "ranger",
      customCard: exilesActorCards.voidSeer,
      token: {
        tokenId: "actor-seer-strip-token",
        label: "Void-seer",
        imageUrl: exilesActorCards.voidSeer.imageUrl,
        title: "Sensor Array",
        subtitle: "Reading echoes",
        tone: "cloth",
      },
      injuryCount: 0,
      distressCount: 2,
    },
    2,
  ),
  createActor(
    {
      actorId: "actor-medic",
      name: "Synthetic Medic",
      callout: "Keeping the air and blood in the same places.",
      baseLayerSlug: "healer",
      tacticalRoleSlug: "ranger",
      customCard: exilesActorCards.syntheticMedic,
      token: {
        tokenId: "actor-medic-token",
        label: "Medic",
        imageUrl: exilesActorCards.syntheticMedic.imageUrl,
        title: "Life Support",
        subtitle: "Repressurizing",
        tone: "monster",
      },
      injuryCount: 1,
      distressCount: 1,
    },
    3,
  ),
];

