import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import { test } from "node:test";
import { gitSourcePaths, inspectLengths, physicalLines } from "./check-file-lengths.mjs";

test("physical lines include blanks and omit only the final newline sentinel", () => {
  assert.equal(physicalLines(""), 0);
  assert.equal(physicalLines("one\n\n"), 2);
  assert.equal(physicalLines("one\r\n\r\n"), 2);
  assert.equal(physicalLines("one\rtwo"), 2);
});

test("300/301/350/351 boundaries and exact exceptions", () => {
  const root = mkdtempSync(join(tmpdir(), "length guard "));
  try {
    mkdirSync(join(root, "spec"));
    for (const n of [300, 301, 350, 351]) writeFileSync(join(root, "spec", `${n}.ts`), "x\n".repeat(n));
    const paths = [300, 301, 350, 351].map((n) => `spec/${n}.ts`);
    assert.deepEqual(inspectLengths(root, paths).map(({ path, level }) => [path, level]), [
      ["spec/301.ts", "warning"], ["spec/350.ts", "warning"], ["spec/351.ts", "error"],
    ]);
    assert.equal(inspectLengths(root, paths, { "spec/351.ts": "generated by tool" }).some((f) => f.level === "error"), false);
    assert.equal(inspectLengths(root, paths, { "spec/300.ts": "stale" })[0].reason, "stale exception");
    assert.equal(inspectLengths(root, paths, { "spec/351.ts": " " }).some((f) => f.reason === "invalid exception"), true);
  } finally { rmSync(root, { recursive: true, force: true }); }
});

test("git inventory includes untracked source with spaces and excludes ignored output", () => {
  const root = mkdtempSync(join(tmpdir(), "length git "));
  try {
    execFileSync("git", ["init", "-q"], { cwd: root });
    mkdirSync(join(root, "spec"));
    mkdirSync(join(root, "apps", "server", "dist"), { recursive: true });
    writeFileSync(join(root, ".gitignore"), "apps/server/dist/\n");
    writeFileSync(join(root, "spec", "with space.ts"), "x");
    writeFileSync(join(root, "apps", "server", "dist", "built.ts"), "x");
    const paths = gitSourcePaths(root);
    assert.ok(paths.includes("spec/with space.ts"));
    assert.ok(!paths.includes("apps/server/dist/built.ts"));
  } finally { rmSync(root, { recursive: true, force: true }); }
});
