import { extendTailwindMerge } from "tailwind-merge";

export const cn = extendTailwindMerge({
  extend: {
    // ↓ Add values to existing theme scale or create a new one
    theme: {
      color: [
        "fire-1",
        "fire-2",
        "fire-3",
        "fire-4",
        "fire-5",
        "blood-1",
        "blood-2",
        "blood-3",
        "blood-4",
        "blood-5",
        "lightning-1",
        "lightning-2",
        "lightning-3",
        "lightning-4",
        "lightning-5",
        "acid-1",
        "acid-2",
        "acid-3",
        "acid-4",
        "acid-5",
        "curse-1",
        "curse-2",
        "curse-3",
        "curse-4",
        "curse-5",
        "kac-steel",
        "kac-steel-light",
        "kac-steel-dark",
        "kac-iron",
        "kac-iron-light",
        "kac-iron-dark",
        "kac-blood",
        "kac-blood-light",
        "kac-blood-dark",
        "kac-fire",
        "kac-fire-light",
        "kac-fire-lightest",
        "kac-fire-dark",
        "kac-bone",
        "kac-bone-light",
        "kac-bone-dark",
        "kac-bone-darker",
        "kac-skin",
        "kac-skin-light",
        "kac-skin-dark",
        "kac-gold",
        "kac-gold-light",
        "kac-gold-dark",
        "kac-gold-darker",
        "kac-cloth",
        "kac-cloth-light",
        "kac-cloth-lightest",
        "kac-cloth-dark",
        "kac-curse",
        "kac-curse-light",
        "kac-curse-dark",
        "kac-monster",
        "kac-monster-light",
        "kac-monster-dark",
        "special",
        "success",
        "partial",
        "chaos",
        "fumble",
      ],
    },
    conflictingClassGroupModifiers: {} as any,
    classGroups: {
      "font-size": ["2xs", "3xs"],
      "font-family": [
        "jd-logo",
        "jd-prequel-body",
        "jd-heading",
        "jd-body",
        "dtHeading",
        "kacBody",
        "kacLogo",
        "kacHeading",
        "mmHeading",
        "mkHeading",
        "mkBody",
      ],
    } as any,
  },
});
